### ISSUE TITLE
Installing devspace via yarn fails

### ISSUE THREAD

**Issue by ashconnell** [devspace-cloud/devspace#772]
**What happened?**  
Installing via `npm install -g devspace` works as expected but after installing via `yarn global add devspace` the devspace commands fail

**How can we reproduce the bug?** (as minimally and precisely as possible)  
```
Ashs-MBP:glow-svc ashconnell$ yarn global add devspace
yarn global v1.12.3
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Installed "devspace@4.1.3" with binaries:
      - devspace
✨  Done in 5.38s.
Ashs-MBP:glow-svc ashconnell$ source ~/.bashrc
Ashs-MBP:glow-svc ashconnell$ devspace --help
Finishing installation for DevSpace CLI
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '/Users/ashconnell/.nvm/versions/node/v10.16.0/lib/node_modules/devspace/index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

**Local Environment:**  
- Operating System: Mac
- Yarn: 1.12.3
- Node: 10.16.0 (using nvm)

/kind bug

**Comment by LukasGentele** [comment]
Thanks for reporting this, @ashconnell. We are currently only supporting npm as install method. I can certainly look into making this work with yarn as well. That shouldn't be too hard.

Out of curiosity: Why did you want to install DevSpace via yarn after already successfully installing it via npm beforehand?

**Comment by ashconnell** [comment]
You can probably backlog this. On my host machine I use Yarn for everything - mainly for the monorepo functionality - so I first tried to install using yarn, which failed so I just used npm.

**Comment by LukasGentele** [comment]
Got it. That makes sense. Thanks! Will look into why the yarn install failed.

**Comment by LukasGentele** [comment]
Update: I changed a couple of things in v4.2.0-beta.5 regarding the npm installer which should allow to install DevSpace via yarn as well.

@ashconnell Can you try to re-install DevSpace again using yarn and confirm that this issue is resolved? I tried on my machine using these commands:
```bash
# Uninstall via npm first
npm uninstall -g devspace

# Install via yarn
yarn global add devspace@4.2.0-beta.5
```

**Comment by ashconnell** [comment]
Yep looks to be working! Nice one!

```
Ashs-MBP:tmp ashconnell$ devspace --version
devspace version 4.1.3
Ashs-MBP:tmp ashconnell$ npm uninstall -g devspace

> devspace@4.1.3 preuninstall /Users/ashconnell/.nvm/versions/node/v10.16.0/lib/node_modules/devspace
> node index.js uninstall

? Do you want to remove the global DevSpace config folder ~/.devspace? no
removed 88 packages in 6.192s
Ashs-MBP:tmp ashconnell$ yarn global add devspace@4.2.0-beta.5
yarn global v1.12.3
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Installed "devspace@4.2.0-beta.5" with binaries:
      - devspace
✨  Done in 6.47s.
Ashs-MBP:tmp ashconnell$ source ~/.bashrc
Ashs-MBP:tmp ashconnell$ devspace --version
Finishing installation for DevSpace CLI
Download DevSpace CLI release: https://github.com/devspace-cloud/devspace/releases/download/v4.2.0-beta.5/devspace-darwin-amd64

devspace version 4.2.0-beta.5
```
