### ISSUE TITLE
panic if image yaml is empty

### ISSUE THREAD

**Issue by shaunc** [devspace-cloud/devspace#847]
**What happened?**  

```
devspace dev
[info]   Using kube context 'local'
[info]   Using namespace 'crane-web'
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x78 pc=0x48d1136]

goroutine 1 [running]:
github.com/devspace-cloud/devspace/pkg/devspace/config/versions/v1beta5.(*Config).Upgrade(0xc00014c4d0, 0x65afc60, 0x7c42480, 0x5d126e0, 0xc00014c4d0, 0x1, 0x0)
	/Users/runner/runners/2.162.0/work/devspace/devspace/pkg/devspace/config/versions/v1beta5/upgrade.go:20 +0x116
github.com/devspace-cloud/devspace/pkg/devspace/config/versions.Parse(0xc000598ff0, 0xc0013f4810, 0x65afc60, 0x7c42480, 0x0, 0x0, 0x0)
	/Users/runner/runners/2.162.0/work/devspace/devspace/pkg/devspace/config/versions/versions.go:91 +0x27a
github.com/devspace-cloud/devspace/pkg/devspace/config/loader.(*configLoader).parseConfig(0xc0013f4840, 0xc0013f4960, 0xc000598ff0, 0xc000598ff0, 0x0, 0x0)
	/Users/runner/runners/2.162.0/work/devspace/devspace/pkg/devspace/config/loader/parse.go:130 +0x22f
github.com/devspace-cloud/devspace/pkg/devspace/config/loader.(*configLoader).LoadFromPath(0xc0013f4840, 0xc0013f4960, 0x6075dd0, 0xd, 0x65113c0, 0xc000609a20, 0x0)
	/Users/runner/runners/2.162.0/work/devspace/devspace/pkg/devspace/config/loader/get.go:177 +0x185
github.com/devspace-cloud/devspace/pkg/devspace/config/loader.(*configLoader).loadInternal(0xc0013f4840, 0x601, 0xc0013812f0, 0x10, 0x0)
	/Users/runner/runners/2.162.0/work/devspace/devspace/pkg/devspace/config/loader/get.go:207 +0xab
github.com/devspace-cloud/devspace/pkg/devspace/config/loader.(*configLoader).Load(0xc0013f4840, 0xc0010ea9a0, 0xc00109db60, 0x59bd33f)
	/Users/runner/runners/2.162.0/work/devspace/devspace/pkg/devspace/config/loader/get.go:145 +0x30
github.com/devspace-cloud/devspace/cmd.(*DevCmd).loadConfig(0xc00055a000, 0xc000290690, 0xc0013f4960, 0x0)
	/Users/runner/runners/2.162.0/work/devspace/devspace/cmd/dev.go:592 +0x4c
github.com/devspace-cloud/devspace/cmd.(*DevCmd).Run(0xc00055a000, 0xc000ea2280, 0x7c9c888, 0x0, 0x0, 0x0, 0x0)
	/Users/runner/runners/2.162.0/work/devspace/devspace/cmd/dev.go:180 +0x510
github.com/spf13/cobra.(*Command).execute(0xc000ea2280, 0x7c9c888, 0x0, 0x0, 0xc000ea2280, 0x7c9c888)
	/Users/runner/runners/2.162.0/work/devspace/devspace/vendor/github.com/spf13/cobra/command.go:826 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0xc000e87180, 0x7c9c888, 0xc000e87180, 0x0)
	/Users/runner/runners/2.162.0/work/devspace/devspace/vendor/github.com/spf13/cobra/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/runner/runners/2.162.0/work/devspace/devspace/vendor/github.com/spf13/cobra/command.go:864
github.com/devspace-cloud/devspace/cmd.Execute()
	/Users/runner/runners/2.162.0/work/devspace/devspace/cmd/root.go:70 +0xbd
main.main()
	/Users/runner/runners/2.162.0/work/devspace/devspace/main.go:17 +0x3e
```
**What did you expect to happen instead?**  

(no crash)

**How can we reproduce the bug?** (as minimally and precisely as possible)  

devspace.yaml containing:
```
version: v1beta5
images:
  foo:
```

**Local Environment:**  
Mac, devspace 4.3.4

**Anything else we need to know?**  

Should return error rather than panicking.

/kind bug

**Comment by FabianKramm** [comment]
@shaunc thanks for spotting this issue! We will fix this ASAP
