### ISSUE TITLE
devspace sync --config in subdirectory fails

### ISSUE THREAD

**Issue by igoooor** [devspace-cloud/devspace#937]
**What happened?**  
I ran `devspace sync --config ops/devspace/devspace.yaml` and the output is
```
[info]   Using kube context 'docker-for-desktop'
[info]   Using namespace 'default'
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x5a02380]

goroutine 1 [running]:
github.com/devspace-cloud/devspace/cmd.(*SyncCmd).Run(0xc001360280, 0x65f9fe0, 0x7d0e448, 0xc001373400, 0xc0011f0ce0, 0x0, 0x2, 0x0, 0x0)
	/Users/runner/runners/2.164.0/work/devspace/devspace/cmd/sync.go:171 +0x520
github.com/devspace-cloud/devspace/cmd.NewSyncCmd.func1(0xc001373400, 0xc0011f0ce0, 0x0, 0x2, 0x0, 0x0)
	/Users/runner/runners/2.164.0/work/devspace/devspace/cmd/sync.go:59 +0x64
github.com/spf13/cobra.(*Command).execute(0xc001373400, 0xc0011f0ca0, 0x2, 0x2, 0xc001373400, 0xc0011f0ca0)
	/Users/runner/runners/2.164.0/work/devspace/devspace/vendor/github.com/spf13/cobra/command.go:826 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0xc00134a000, 0x7d0e448, 0xc00134a000, 0x0)
	/Users/runner/runners/2.164.0/work/devspace/devspace/vendor/github.com/spf13/cobra/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/runner/runners/2.164.0/work/devspace/devspace/vendor/github.com/spf13/cobra/command.go:864
github.com/devspace-cloud/devspace/cmd.Execute()
	/Users/runner/runners/2.164.0/work/devspace/devspace/cmd/root.go:70 +0xbd
main.main()
	/Users/runner/runners/2.164.0/work/devspace/devspace/main.go:17 +0x3e
```
If I copy my `ops/devspace/devspace.yaml` in my current directory and run `devspace sync --config devspace.yaml` it works properly

**Local Environment:**  
- Operating System: mac
- Deployment method: helm
- devspace version 4.5.0

**Kubernetes Cluster:**  
- Cloud Provider: local with docker for mac
- Kubernetes Version: 1.16

/kind bug

**Comment by FabianKramm** [comment]
@igoooor thanks for opening this issue! Yes you are also correct with this one, I'll fix this aswell
